project_id = "oxpofifrabgethoujvjn"

[functions.consult-ethics]
verify_jwt = true

[functions.translate-term]
verify_jwt = true

[functions.evaluate-performance]
verify_jwt = true

[functions.advanced-terminology-search]
verify_jwt = false

[functions.practice-scenario]
verify_jwt = true